book/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :books
root 'welcome#index'
end

book/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

book/app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true,length: {minimum: 5}
end

book/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

book/app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		@books = Book.all
	end

	def show
		@book = Book.find(params[:id])
	end

	def new
		@book = Book.new
	end

	def edit
		@book = Book.find(params[:id])
	end

	def create
		#@book = Book.new(params[:book])
		@book = Book.new(book_params)

		if @book.save
			@book.save
			redirect_to @book
		else
			render 'new'
		end
	end

	def update
		@book = Book.find(params[:id])

		if @book.update(book_params)
			redirect_to @book
		else
			render 'edit'
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy

		redirect_to books_path
	end

	private
		def book_params
			params.require(:book).permit(:title, :text)
		end
end

book/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

book/app/helpers/application_helper.rb
module ApplicationHelper
end

book/app/helpers/books_helper.rb
module BooksHelper
end

book/app/helpers/welcome_helper.rb
module WelcomeHelper
end

book/app/views/books/edit.html.erb
<h1>新しい書籍</h1>

<%= form_for :book, url: books_path(@book), method: :patch do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

<%= link_to '戻る', books_path %>

book/app/views/books/index.html.erb
<h1>書籍一覧</h1>

<%= link_to '新しい書籍を登録', new_book_path %>

<table>
	<tr>
		<th>タイトル</th>
		<th>テキスト</th>
		<th colspan="3"></th>
	</tr>

	<% @books.each do |book| %>
	<tr>
		<td><%= book.title %></td>
		<td><%= book.text %></td>
		<td><%= link_to '表示', book_path(book) %></td>
		<td><%= link_to '編集', edit_book_path(book) %></td>
		<td><%= link_to '削除', book_path(book),
				method: :delete,
				data: {confirm: '本当に削除していいですか？'} %>
		</td>
	</tr>
	<% end %>
</table>

book/app/views/books/new.html.erb
<h1>新しい書籍</h1>

<%= form_for :book, url: books_path do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

book/app/views/books/show.html.erb
<p>
<strong>タイトル：</strong>
<%= @book.title %>
</p>

<p>
<strong>テキスト：</strong>
<%= @book.text %>
</p>

<%= link_to '戻る', books_path %>

book/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

book/app/views/welcome/index.html.erb
<h1>Hello Rails!</h1>

<%= link_to '書籍一覧', controller:'books' %>